# Julia 言語 第2回 基本的な構文

ここでは基本的な構文を説明します。  
当然ここでは説明しきれない量の構文がありますので、  
ざっくり説明して、実際にプログラムをかけるところまで行きたいと思います。  
次回以降、さらに必要な知識を追加していきます。  
  
各セルの中身を実際に入力し、自分のエディタでも実行してみましょう。



## 2.1 変数
 
```変数```はデータ(数値、文字列、真偽値など）を格納する場所です。  
```変数名 = 値```  
下記のようにして使います。  

In [1]:
a = 5

5

In [2]:
b = "こんにちは" 

"こんにちは"

In [3]:
c = true

true

ここでは、a,b,c三つの変数を宣言し、値を代入しました。  
データを変数に格納することを、代入といい、演算子```=```を使います。  
ここでの```=```は数学的な等号を意味しません。   

変数名にはUnicodeも使えます。 

In [4]:
α = 1
Δx =0.1

0.1

何なら絵文字も使えます。  

In [5]:
🐱 = "ねこ is cat"

"ねこ is cat"

演算子は2.3で説明しますが、変数名の前の```*``` 乗算演算子は省略できます。

In [6]:
a = 5
2a

10

円周率はデフォルトで入ってます。

In [7]:
π

π = 3.1415926535897...

In [8]:
3π

9.42477796076938

慣例的に、以下のような変数名の付け方をします。  
- 変数名はすべて小文字
- ハイフンは使わない。
- 自作の関数名は大文字から始める。  
- 引数を破壊的関数名には!を最後につける

## 2.2 関数の呼び出し方

```関数```とは処理をひとまとめにしたものです。  
以下のような書式と用語です。  
```関数名(引数)```  
与えた引数(値)に応じて様々な機能を提供してくれます。  
たとえば、```println(引数)``` は引数を画面に表示してくれる関数です。

例えば変数の型を見るtypeof()関数を使ってみましょう。  
  
変数は値を代入された瞬間に、  
どういう種類の値が格納されるのか、メモリ容量を確保すればいいのか、  
という情報を持ちます。  
これを```型(type)```といいます。  
  
次に示すのは、  
println関数に、typeof関数の結果を引数として与えたソースです。  

In [9]:
println( typeof(a) ) #Int64
println( typeof(b) ) #String
println( typeof(c) ) #Bool

Int64
String
Bool


Juliaは様々な変数の型をもっています。例えば

In [10]:
println( typeof(1))
println( typeof(1.0))
println( typeof("文字列はstring"))
println( typeof(1im))
println( typeof(true))
println( typeof(false))

Int64
Float64
String
Complex{Int64}
Bool
Bool


IntはIntgerの略で整数、という意味です。  
末尾の数字は64bit  
より大きい数字を格納できます。  
同様にFloatは浮動小数点のことです。  
1 と 1．0 で型が異なることに注意です。  
同じ種類の型同士であれば四則演算が可能です。  
ここでは同じ種類というのは例えば数値型なら数値型、文字型なら文字型、という程度に覚えておいてください。  
  
※詳細に言うならば、同じ抽象型(Abstract type)のSubtypeなら四則演算が用意されていることが多い、です。  
今は気にしなくておーけーです。  

In [11]:
d = 3
e = 4.5
println(d+e)

7.5


In [12]:
f = "さようなら"
g = "またあいましょう"
println(f*g)

さようならまたあいましょう


In [13]:
h = 5im
println(d + h)

3 + 5im


文字列の連結は```*```です。 他言語ですと+が多いですが、間違えないようにしましょう。   
複素数は数字imで表記します。1imとかとします。  
もちろん違う型同士だと、エラーが出ます。  
  



## 2.3 エラーの見方
プログラムを書くと様々なエラーが発生します。  
インタプリタは、エラーを検知するとエラーの種類や場所に応じてコメントを返します。  
ここでは、エラーの見方を確認します。

In [14]:
i = 10
j = "整数と文字列は足せない。"
println(i + j)

LoadError: MethodError: no method matching +(::Int64, ::String)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:538
  +(::T, !Matched::T) where T<:Union{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8} at int.jl:86
  +(::Integer, !Matched::Integer) at int.jl:918
  ...

コンパイルエラーが生じると、  
様々な情報となぜエラーが出たか、おしえてくれます。  
ここでは、
```MethodError: no method matching +(::Int64, ::String)```
というタイトルです。  
juliaは内部で、四則演算すら関数として処理しています。  
```a + b``` と  
```+(a,b)``` は同じ意味です。

In [15]:
a = 1
b = 2
println(+(a,b))

3


先ほどのエラーでは、Int64型と、String型を引数にとる関数+はありません。  
という意味です。  
```
Stacktrace:
 [1] top-level scope at In[23]:3
 [2] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091
```
の部分では、どこでこのエラーを感知したか、が書いてあります。  
```[1]```ここが該当です。 若い番号から見ていけばいいと思います。  
23セルの3行目、と書いてあります。   
```[2]```はもっと深い階層、＋の定義部分です。  
実際には様々なエラーがありますが、  
大体理由が書いてあり、デバッグの重要なヒントです。  
No method matchingを検出した場合には、  
1．引数の型が適切か  
2．変数のはずなのに関数適用してないか。(不必要なカッコがないか)  
等を確認します。
  
エラーの数は数多ありますが、以下のものも頻出です。  

In [16]:
nondefined 

LoadError: UndefVarError: nondefined not defined

UndefVarError: xxxx not definedは宣言されていない変数を使ったときに出るエラーです。  
誤字脱字がないか、チェックしてみましょう。  

## 2.4 演算子

演算子は演算を表すシンボルです。  
たくさんあるので、取り急ぎ必要なものだけピックアップします。

**算術演算子**

|式	   | 名前|	説明|
| ---- | ---- | ---- |
|+x   |  単項加算|	恒等演算|
|-x   | 	単項減算|	加算の逆元への関数|
|x + y|	二項加算|	加算を実行|
|x - y|	二項減算|	減算を実行|
|x * y|	乗算    |	乗算を実行|
|x / y|	除算    |	除算を実行|
|x ÷ y|	整数除算|	x / y, 整数に切り捨て|
|x \ y|	逆除算  |	y / xと同等|
|x ^ y|	巾      |	x の y乗|
|x % y|	剰余算  |	rem(x,y)と同等|
|x += y|	加算代入  |	x = x + yと同等|
|x -= y|	減算代入  |	x = x ― yと同等|

**比較演算子**

|  演算  |  名前  |
| ----  |  ---- |
|  ==  |  等号  |
|  !=  |  ≠不等号  |
|  <   |  未満  |
|  <=  |  以下  |
|  >  |  より大きい  |
|  >=  |  以上  |


後はここ見てください。  
https://mnru.github.io/julia-doc-ja-v1.0/manual/mathematical-operations.html  
必要なときに各種説明します。  

In [17]:
a = 5
b = 2

println(a / b)
println(a % b)
println(a \ b)
a += b
println(a)

2.5
1
0.4
7


逆除算は行列計算の時にも使いますが、  
数値の時は a分のbという読み方になります。


In [18]:
a = 2
b = 3

println(a<b)
println(a>b)
println(a!=b)

true
false
true


## 2.5 コレクション
  
コレクションとは、1つの変数に複数の値を保持できるタンスのようなものです。  
コレクションの種類にはリスト、タプル、辞書などがあります。



### 2.5.1 ベクトル(リスト) 

ベクトルは**データ長可変のコレクション**です。  
``` a = [2,4,6] ```  
のように定義します。  
ここで、コレクションに含まれる値のことを``` 要素(element) ``` といいます。  
ベクトル ``` a ``` には三つの要素が含まれています。  
一番目は2、二番目は4、三番目は6です。  
どこの場所に含まれているか、それを示す番号を``` 添え字(index) ``` または ``` インデックス ``` といいます。  
リストの要素を参照するためには下記のようにします。  
  
また、Juliaのベクトルは列方向に配置されます。  
視覚的に改行を用いて
```
b = [
2
4
6
]
```
という風に定義することも可能です。  

要素へのアクセスは、  
```a[インデックス] ``` とします。  
Julia言語は**先頭要素へのアクセスは添え字1番**からです。  
これはFortlanなどと同じですが、C言語やPythonとは異なります。  
 


In [19]:
a = [2,4,6]
println( a )

println( a[1] )
println( a[2] )
println( a[3] )
b = [
    2
    4
    6
]

println( a==b)


[2, 4, 6]
2
4
6
true


Julia のベクトルは、次元数1の、  
``` Array[要素の型,次元数]```  
という型で定義されています。  
多次元配列については最後に書きます。  

In [20]:
println(typeof(a))

Array{Int64,1}


Array型を定義する関数は多数用意されています。  
以下にいくつか紹介します。  

In [21]:
a = zeros(3)

3-element Array{Float64,1}:
 0.0
 0.0
 0.0

In [22]:
b = fill(5,3)

3-element Array{Int64,1}:
 5
 5
 5

In [23]:
c = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

要素を追加したいときには、push!()関数を使います。  
他にも配列操作のための関数が用意されています。  

In [24]:
a = [2,4,6]
println(a)

 # 末尾への追加
push!(a,8)
println(a)

 # 末尾のとりだし
b = pop!(a)
println(b)
println(a)

#i番目に要素を挿入
insert!(a, 2, 10)
println(a)

#i番目を削除  
deleteat!(a, 3)
println(a)

[2, 4, 6]
[2, 4, 6, 8]
8
[2, 4, 6]
[2, 10, 4, 6]
[2, 10, 6]


Julia言語では慣例的に、**引数を破壊する関数には関数名の末尾に``` ! ```をつけます**。  
  
``` push!(a) ``` をする前のa と、した後のaは異なるものです。  

### 2.5.2 タプル
タプルはリストと違い **変更不可能なコレクション** です。  
変更不可能なことを**inmutable**  
変更可能なことを**mutable**  
といいます。  
宣言の仕方は  
タプル名 = (要素, 要素)
とします。  


In [25]:
class = ("B4", "M1", "M2")
println( class[1] )
println( class[2] )
println( class[3] )

B4
M1
M2


In [26]:
class[1] = "D1"

LoadError: MethodError: no method matching setindex!(::Tuple{String,String,String}, ::String, ::Int64)

### 2.5.3 辞書
辞書は **要素がキーと値がペアになったコレクション** です。  
辞書はmutableです。  
辞書名=Dict(キー=>値,キー=>値)とします。

In [27]:
Bz = Dict("Vocal" => "Inaba", "Guiter" => "Matsumoto")

println(Bz["Guiter"])
println(Bz["Vocal"])

Matsumoto
Inaba


他言語学習者向け：  
ここで、``` =>```という演算子はPairというオブジェクトを実現しています。  
[Pairオブジェクトの定義](https://github.com/JuliaLang/julia/blob/2fc3dcdaecc0f77fee56400ee80752cc81c8dfb0/base/pair.jl#L3-L16)  
PairはFirstとSecondという要素を持つ構造体です。  
構造体については後程やります。  
Dict関数にPairオブジェクトを与えることで、辞書を実現しています。  
Juliaは超低階層のところ以外をJuliaで開発されているうえ、  
すべてのコードはGithubで公開されています。  
コードを読むことによって新たな知見、広く拓かれた書き方が身につくと思います。  

### 2.5.4 Range  
リストと似たようなものに、Range型が用意されています。  
Rangeは``` : ``` を使って表します。  
``` start:stop ```   
``` start:step:stop ```  
とします。  
または``` range() ```関数も用意されています。
``` range(start,length = xx) ```  
これは  
``` start:stop```  
と等価です。  
そのほか、長さを決めたりもできます。

In [28]:
println( 1 : 10) # 要素数は10個です
println( 0 :0.1: 1)
println( range(1, length = 10))
println( range(0, 1, length = 11))
println( range(0, step = 0.1, length =11))

1:10
0.0:0.1:1.0
1:10
0.0:0.1:1.0
0.0:0.1:1.0


### 2.5.5 多次元配列
  
多次元配列は配列の中に配列が入った、いわゆる行列です。  
Juliaでは一次元配列をベクトル、二次元以上の配列を行列(マトリックス)として区別します。  
視覚的に以下のようにも表現できますが



In [29]:
a= [
    1 2 3
    4 5 6
]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

関数を使って生成した方が分かりやすいかと思います。  
ベクトルの時に紹介した関数は多次元配列も容易に作成できます。

In [30]:
a = zeros(2,4)

2×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [31]:
b = ones(2,4)

2×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [32]:
c = fill(10, 2, 4)

2×4 Array{Int64,2}:
 10  10  10  10
 10  10  10  10

## 2.6 条件評価
条件が真のとき(正しいとき)と偽のとき（正しくないとき）の処理を振り分ける構文は以下のようにします。  

```
  if x < y
      println("x is less than y")
  elseif x > y
      println("x is greater than y")
  else
      println("x is equal to y")
  end
```

elseif もしくはelse は省略可能です。  
if --- end  
で一区切り。

In [33]:
x = 10
y = 5

  if x < y
      println("x is less than y")
  elseif x > y
      println("x is greater than y")
  else
      println("x is equal to y")
  end

y = 20

  if x < y
      println("x is less than y")
  elseif x > y
      println("x is greater than y")
  else
      println("x is equal to y")
  end

y= 10

  if x < y
      println("x is less than y")
  elseif x > y
      println("x is greater than y")
  else
      println("x is equal to y")
  end

x is greater than y
x is less than y
x is equal to y


## 2.7 反復操作

反復操作はある条件に従って、複数回同様の処理を繰り返すことを言います。  

### 2.7.1 for
for 文はコレクションを使って繰り返しを行う処理です。  
以下のような構文です。  
```
for i in [correction]


end

```
コレクションの中身がiに代入されます。  
コレクションがすべて使われると、forは終了します。  

In [34]:
a = [1,2,3]
for i in a
    println(i)
end

1
2
3


In [35]:
a = 1 : 10

for x in a
    println(x)
end

1
2
3
4
5
6
7
8
9
10


In [36]:
for n in range(1,5, length = 5)
    for m in range(1,5, length = 5)
        println(n," " ,m," ", (n+m))
    end
end

1.0 1.0 2.0
1.0 2.0 3.0
1.0 3.0 4.0
1.0 4.0 5.0
1.0 5.0 6.0
2.0 1.0 3.0
2.0 2.0 4.0
2.0 3.0 5.0
2.0 4.0 6.0
2.0 5.0 7.0
3.0 1.0 4.0
3.0 2.0 5.0
3.0 3.0 6.0
3.0 4.0 7.0
3.0 5.0 8.0
4.0 1.0 5.0
4.0 2.0 6.0
4.0 3.0 7.0
4.0 4.0 8.0
4.0 5.0 9.0
5.0 1.0 6.0
5.0 2.0 7.0
5.0 3.0 8.0
5.0 4.0 9.0
5.0 5.0 10.0


最後の例のように、繰り返し文は入れ子構造も可能です。  
この入れ子にすることを**ネスト** といいます。  
条件分岐と組み合わせることも当然、可能です。

In [37]:
for n in 1:20
    if n % 2 == 0
        println(n)
    end
end

2
4
6
8
10
12
14
16
18
20


### 2.7.2 while
whileは条件にあうまで、ループを繰り返す処理です。  


In [38]:

while i < 10
   println(i)
   i += 1
end

初期条件でiを宣言する必要があることに気を付けましょう。   

## 2.8 関数
関数は処理をひとまとめにして名前を付けるものです。  
ここまで、println関数や、typeof関数を使いました。  

ここでJuliaの特性として、  
**関数をJITコンパイルにかける**  
というものがあります。  
後程高速化の部分で比較してみますが、juliaの場合、  
すべての処理は関数としてまとめる必要があります。  
  
関数宣言は以下のようにします。  
```
function 関数名(引数)
    処理
end
```


In [39]:
function retdouble!(x)
    x = 2x
    return x
end

a = 10
retdouble!(a)

20

return を明示して、xを関数の外に出しています。  
このことを、**結果を返す**といいます。  
Juliaの場合、returnを明示しなくても、  
最後に評価された値が返されるので、上の関数では  
returnがなくてもあっても同じです。  

関数としてまとめる部分は、  
- 処理が複数回出てくる
- 計算処理を含み重い部分
- 処理が複雑で、デバッグに手間取りそうな部分  
などが考えられます。  
最初のうちは手当たり次第に関数化してしまってもいいと思います。  
しないよりましです。

単純な関数であれば、
```f(x) = 関数 ```とすることができます。  


In [2]:
f(x) = x*2 + 4x + 3
println(f(2))
println(f(3))

15
21


In [5]:
#複数変数も可能です。
f(x,y) = x^2 + y^2 + 1
println( f(1,2))
println( f(2,3))

6
14


## 2.9 マクロ
 
関数は処理をひとまとめにして名前を付けるものでした。  
マクロは**プログラムの構文自体を書き換えて、インタプリタに渡す機能です。**  
このようにプログラムによって、隠匿してプログラムを書き換えることを  
**メタプログラミング** といいます。  
近代プログラミング言語には導入されていることが多いです  
  
以下のプログラムを見てみましょう。   

In [63]:
a = zeros(3,3)

@show a;

a = [0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]


@show マクロは変数の型や内容をREPLに表示するマクロです。  
printlnと似てます。比較してみましょう。  

In [41]:
println(a)

[0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]


@show のいいところは、型定義の段階で、  
どういう情報を明示するか、開発者側が定義できるということです。  
デバッグ時には変数の中身を随時確認しながら  

printlnより明確な情報が得られますので、  
今後表示はすべて@showを使います。  
  
マクロも数多用意されています(自分で定義もできますが、)  
他に便利なものとしては、@timeがあります。  


In [52]:
count = 0
@time for i in 1:100000
    yakusuu=0
    for j in 1:i
        if i%j == 0
            yakusuu += 1
        end

    end
    if(yakusuu==2) 
        global count+=1 
    end
end
@show count

 10.717906 seconds (9.08 k allocations: 141.891 KiB)
count = 9592


9592

上の関数は素数の数をカウントするプログラムです。  
(コード最適化はしていません。偶数はぶいたりでもっと早くなります。)  
for の前に@timeを付けることで、  
処理にかかる時間とメモリアロケート(確保量)をカウントすることができます。  
私のパソコンですと、大体11秒ぐらいかかりました。  
12行目のglobalについてはあとで説明します。  
  
さて、上記の処理を関数化してみましょう。

In [53]:
function sosuu()
    count = 0
    for i in 1:100000
        yakusuu=0
        for j in 1:i
            if i%j == 0
                yakusuu += 1
            end

        end
        if(yakusuu==2) 
            count+=1 
        end
    end
    @show count
end
@time sosuu()

count = 9592
  9.619734 seconds (36 allocations: 1.062 KiB)


9592

関数化前と比較して1秒と少し早くなりました。  
関数化するだけでコンパイルがかかり高速化します。
    
   
  
ちなみにpythonで同じのを実行したら、397秒かかりました。  
壊れたかと思いました。

このように、マクロを使うことでより簡便に便利な機能を享受することが可能です。  
他にも  
様々なマクロがありますので、折をみて紹介していきます。  


#### スコープについて  
Juliaはforや関数の外にある変数を書き換えるときには、  
上記のようにglobalを付ける必要があります。  
このように、プログラムが変数を参照できる範囲のことを```スコープ```といいます。  
  
Juliaは、```グローバルスコープ```と```ローカルスコープ```があり、  
for、while、関数定義、structなどは新しいローカルスコープを導入します。  
一旦ローカルスコープを作ってしまえば、その中でネストされても、上位のローカルスコープは参照可能です。  
ローカルスコープから、グローバルスコープを参照する場合には  
global を付ける必要があります。
```
#####グローバルスコープ-ここから-
count = 0

@time for i in 1:100000    #****ローカルスコープ-ここから-
    yakusuu=0
    for j in 1:i
        if i%j == 0
            yakusuu += 1
        end

    end
    if(yakusuu==2) 
        global count+=1 
    end
end                      #****ローカルスコープ-ここまで-

@show count
#####グローバルスコープ-ここまで-
```
  
ローカルスコープ内からグローバルスコープのcountを参照しているので、
globalを付ける必要があります。  
  
一方、関数化した方では、関数自体がローカルスコープを作っているため、  
関数内のconstにアクセスするのにglobalは必要ありません。  

## 2.10 ドット演算子とブロードキャスト
ここでは、ドット演算子とブロードキャストについて説明する。  
プロットする場合など  
x = range(0,stop = 10, length =200)などとして、  
x軸を決めて、表示したい関数、例えばy = sin(x)としたくなります。  
しかしながら、rangeの提供する型UnitRange{T}に対しての関数は用意されておらず、    
```sin(x::UnitRange{T})  ```
はno method matchingとなります。  
  
若干脱線しますが、  
このレンジが提供する型UnitRange{T}のTはInt64やFloat64など、  
レンジ内の要素が持つ型になります、  
他にもArray{T,1}などでこのような書き方をします。  

例えば、プロットではなくても、  
```
a = [
1 4
5 6
]
```
のような二次元配列すべてに大して同様の演算をしたい、例えば2をかけたりしたい場合、  
fill(2,2,2)を使い新たに行列を用意するのは非常に非効率です。  
  
他にも座標マップ上の複素電界すべてに対して絶対値を取りたい、のような場合もあるでしょう。  
このような場合、ドット演算子を使ったブロードキャストが有効です。  

In [58]:
a = range(-2π,stop = 6π, length = 10)
# sin(a) エラー
@show sin.(a)

sin.(a) = [2.4492935982947064e-16, 0.34202014332566866, -0.6427876096865393, 0.8660254037844387, -0.9848077530122081, 0.984807753012208, -0.8660254037844387, 0.6427876096865384, -0.34202014332566777, -7.347880794884119e-16]


10-element Array{Float64,1}:
  2.4492935982947064e-16
  0.34202014332566866
 -0.6427876096865393
  0.8660254037844387
 -0.9848077530122081
  0.984807753012208
 -0.8660254037844387
  0.6427876096865384
 -0.34202014332566777
 -7.347880794884119e-16

In [2]:
a = 1:10
@show a .+ 1
# a + 1 これはエラー

a .+ 1 = 2:11


2:11

In [1]:
a = [
    1 2 3
    4 5 6
    7 8 9]
@show a .* 2
# a * 2 これはエラー

a .* 2 = [2 4 6; 8 10 12; 14 16 18]


3×3 Array{Int64,2}:
  2   4   6
  8  10  12
 14  16  18

自作の関数にも当然適用可能です。  


In [8]:
f(x) = x^2 + 2x + 1
i = 1:4
@show f.(i)

f.(i) = [4, 9, 16, 25]


4-element Array{Int64,1}:
  4
  9
 16
 25

二次元の座標マップを作るためには、  
xとyのrangeを用意して、  
```xと、yの転置行列 y' ```  
に対してブロードキャストを使えばいいです。  

In [15]:
x = range(-1, stop =1, length =5)
y = range(-1, stop =1, length =5)
@show exp.(x.^2 .+ y'.^2)

exp.(x .^ 2 .+ y' .^ 2) = [7.38905609893065 3.4903429574618414 2.718281828459045 3.4903429574618414 7.38905609893065; 3.4903429574618414 1.6487212707001282 1.2840254166877414 1.6487212707001282 3.4903429574618414; 2.718281828459045 1.2840254166877414 1.0 1.2840254166877414 2.718281828459045; 3.4903429574618414 1.6487212707001282 1.2840254166877414 1.6487212707001282 3.4903429574618414; 7.38905609893065 3.4903429574618414 2.718281828459045 3.4903429574618414 7.38905609893065]


5×5 Array{Float64,2}:
 7.38906  3.49034  2.71828  3.49034  7.38906
 3.49034  1.64872  1.28403  1.64872  3.49034
 2.71828  1.28403  1.0      1.28403  2.71828
 3.49034  1.64872  1.28403  1.64872  3.49034
 7.38906  3.49034  2.71828  3.49034  7.38906

最後の例のように、. が多くなるともうわけわかんない、ってなると思います。  
ドットを自動でつける@.マクロが存在します。   

In [16]:
x = range(-1, stop =1, length =5)
y = range(-1, stop =1, length =5)
@show @. exp(x^2 + y'^2)

#= In[16]:3 =# @__dot__(exp(x ^ 2 + y' ^ 2)) = [7.38905609893065 3.4903429574618414 2.718281828459045 3.4903429574618414 7.38905609893065; 3.4903429574618414 1.6487212707001282 1.2840254166877414 1.6487212707001282 3.4903429574618414; 2.718281828459045 1.2840254166877414 1.0 1.2840254166877414 2.718281828459045; 3.4903429574618414 1.6487212707001282 1.2840254166877414 1.6487212707001282 3.4903429574618414; 7.38905609893065 3.4903429574618414 2.718281828459045 3.4903429574618414 7.38905609893065]


5×5 Array{Float64,2}:
 7.38906  3.49034  2.71828  3.49034  7.38906
 3.49034  1.64872  1.28403  1.64872  3.49034
 2.71828  1.28403  1.0      1.28403  2.71828
 3.49034  1.64872  1.28403  1.64872  3.49034
 7.38906  3.49034  2.71828  3.49034  7.38906

一次元っぽく関数宣言をしておいて、@.を付けてしまえばいいわけです。